# Generated by Django 4.2.3 on 2023-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
