# Generated by Django 4.2.3 on 2023-08-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='identifier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='record',
            name='religious_profession',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='script',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='sex_deceased',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='sex_dedicator',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='centuries',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Estimated century/ies'),
        ),
        migrations.AlterField(
            model_name='record',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='inscription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='inscription_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='mentioned_placenames',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='period',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Historical period'),
        ),
        migrations.AlterField(
            model_name='record',
            name='site_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Religious symbol'),
        ),
        migrations.AlterField(
            model_name='record',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('identifier', 'source')},
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_identifier',
        ),
    ]
