# Generated by Django 4.2.3 on 2023-08-22 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_record_record_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_identifier',
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='centuries',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Estimated century/ies'),
        ),
        migrations.AlterField(
            model_name='record',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='inscription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='inscription_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='mentioned_placenames',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='period',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Historical period'),
        ),
        migrations.AlterField(
            model_name='record',
            name='site_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Religious symbol'),
        ),
        migrations.AlterField(
            model_name='record',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
