# Generated by Django 4.2.2 on 2023-10-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_record_centuries_alter_record_inscription_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Century',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='centuries',
        ),
        migrations.RemoveField(
            model_name='record',
            name='inscription_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='language',
        ),
        migrations.RemoveField(
            model_name='record',
            name='script',
        ),
        migrations.RemoveField(
            model_name='record',
            name='site_type',
        ),
        migrations.AddField(
            model_name='record',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.primarycategory'),
        ),
        migrations.AddField(
            model_name='record',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.secondarycategory'),
        ),
        migrations.AddField(
            model_name='record',
            name='estimated_centuries',
            field=models.ManyToManyField(to='data.century', verbose_name='Estimated century/ies'),
        ),
        migrations.AddField(
            model_name='record',
            name='languages',
            field=models.ManyToManyField(to='data.language'),
        ),
        migrations.AddField(
            model_name='record',
            name='scripts',
            field=models.ManyToManyField(to='data.script'),
        ),
    ]
