# Generated by Django 4.2.3 on 2023-08-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_uuid_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='religious_profession',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='script',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='sex_deceased',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='sex_dedicator',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
