# Generated by Django 4.2.11 on 2024-03-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_century_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sex_deceased',
            field=models.CharField(blank=True, choices=[('', '-'), ('female', 'Female'), ('male', 'Male'), ('female-child', 'Female (child)'), ('male-child', 'Male (child)'), ('child', 'Child')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='sex_dedicator',
            field=models.CharField(blank=True, choices=[('', '-'), ('female', 'Female'), ('male', 'Male'), ('female-child', 'Female (child)'), ('male-child', 'Male (child)'), ('child', 'Child')], default='', max_length=255),
        ),
    ]
